name = "roadmap"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2024-03-14"

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

[site]
bucket = ".output/public"
